Topic:
  - class: Topic::Archive
    table: archived_topics

Reply:
  - class: Reply::Archive
    table: archived_replies

Post:
  - class: Post::Archive
    table: archived_posts

# Doesn't work with Devise; don't use!
# User:
#   - class: User::Archive
#     table: archived_users
